# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20190330_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='constraintId',
            new_name='constraint',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prizePoolId',
            new_name='prizePool',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='projectId',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='sceneId',
            new_name='scene',
        ),
        migrations.AlterField(
            model_name='project',
            name='downTime',
            field=models.BigIntegerField(default=0, verbose_name='下线时间'),
        ),
    ]
