# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-30 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190330_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='constraint',
            new_name='constraintId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='prizePool',
            new_name='prizePoolId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='project',
            new_name='projectId',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='scene',
            new_name='sceneId',
        ),
    ]
