# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20190330_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='任务名称'),
        ),
    ]
