# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-31 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20190330_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.URLS'),
        ),
    ]
