# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20190331_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='urls',
        ),
        migrations.AddField(
            model_name='urls',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.Task'),
        ),
    ]
