# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-31 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20190331_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='goUrl',
            field=models.CharField(max_length=700, null=True, verbose_name='gourl'),
        ),
        migrations.AddField(
            model_name='task',
            name='platformBean',
            field=models.CharField(max_length=400, null=True, verbose_name='platformBean'),
        ),
        migrations.DeleteModel(
            name='URLS',
        ),
    ]
