# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-01 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20190331_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='atv',
        ),
        migrations.RemoveField(
            model_name='task',
            name='iph',
        ),
        migrations.RemoveField(
            model_name='task',
            name='web',
        ),
    ]
