# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_auto_20190402_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='图片1'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image2',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='图片2'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image3',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='图片3'),
        ),
        migrations.AlterField(
            model_name='task',
            name='image4',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='图片4'),
        ),
    ]
