# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20190403_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='imageUrl',
            field=models.CharField(max_length=300, null=True, verbose_name='图片地址'),
        ),
    ]
