# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_task_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='autoSendPrize',
            field=models.IntegerField(choices=[(0, '开'), (1, '关')], default=1, verbose_name='自动发奖'),
        ),
        migrations.AddField(
            model_name='task',
            name='hot',
            field=models.IntegerField(choices=[(0, '开'), (1, '关')], default=1, verbose_name='热门'),
        ),
        migrations.AlterField(
            model_name='task',
            name='onOff',
            field=models.IntegerField(choices=[(0, '开'), (1, '关')], default=1, verbose_name='开关'),
        ),
    ]
