# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-04 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_auto_20190404_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createTime',
            field=models.BigIntegerField(default=0),
        ),
    ]
