# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0023_auto_20190405_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Image2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Image3',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Image4',
            new_name='image4',
        ),
    ]
