# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0024_auto_20190405_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imageUrl',
            new_name='imageUrlBean',
        ),
    ]
