# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0025_auto_20190405_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createTime',
            field=models.BigIntegerField(default=0),
        ),
    ]
