# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0026_project_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='memo',
            field=models.TextField(null=True, verbose_name='项目描述'),
        ),
    ]
