# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0027_auto_20190405_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='downTime',
            field=models.BigIntegerField(null=True, verbose_name='下线时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publishTime',
            field=models.BigIntegerField(null=True, verbose_name='上线时间'),
        ),
    ]
