# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-05 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0028_auto_20190405_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='buttonLabel1',
            field=models.CharField(max_length=300, null=True, verbose_name='项目详情文案'),
        ),
    ]
