# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0031_conpontype_couponpool'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conpontype',
            table='conpontype',
        ),
        migrations.AlterModelTable(
            name='couponpool',
            table='conponpool',
        ),
    ]
