# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0032_auto_20190406_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpool',
            name='number',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='面额'),
        ),
    ]
