# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0033_auto_20190406_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpool',
            name='endTime',
            field=models.BigIntegerField(default=0, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='couponpool',
            name='startTime',
            field=models.BigIntegerField(default=0, verbose_name='开始时间'),
        ),
    ]
