# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-06 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0035_auto_20190406_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponpool',
            name='prizeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Conpontype'),
        ),
    ]
